//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NautilusREST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asignatura_grado
    {
        public int id { get; set; }
        public int asignatura_id { get; set; }
        public int grado_id { get; set; }
    
        public virtual asignatura asignatura { get; set; }
        public virtual grado grado { get; set; }
    }
}
