//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NautilusREST.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nautilus_entities : DbContext
    {
        public nautilus_entities()
            : base("name=nautilus_entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<area> area { get; set; }
        public virtual DbSet<asignatura> asignatura { get; set; }
        public virtual DbSet<asignatura_grado> asignatura_grado { get; set; }
        public virtual DbSet<aula> aula { get; set; }
        public virtual DbSet<curso> curso { get; set; }
        public virtual DbSet<detalle_horario> detalle_horario { get; set; }
        public virtual DbSet<grado> grado { get; set; }
        public virtual DbSet<horarios> horarios { get; set; }
        public virtual DbSet<institucion> institucion { get; set; }
        public virtual DbSet<notas> notas { get; set; }
        public virtual DbSet<profesor> profesor { get; set; }
        public virtual DbSet<sede> sede { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<area_with_count_asignaturas> area_with_count_asignaturas { get; set; }
        public virtual DbSet<estudiante> estudiante { get; set; }
    }
}
