//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NautilusREST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notas
    {
        public int id { get; set; }
        public Nullable<double> n1 { get; set; }
        public Nullable<double> n2 { get; set; }
        public Nullable<double> n3 { get; set; }
        public Nullable<double> n4 { get; set; }
        public int horarios_id { get; set; }
        public int estudiante_id { get; set; }
    
        public virtual estudiante estudiante { get; set; }
        public virtual horarios horarios { get; set; }
    }
}
